receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  presidio_redaction:
    anonymizer_endpoint: http://localhost:5001/anonymize
    analyzer_endpoint: http://localhost:5002/analyze

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
