receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  presidio_redaction:
    presidio_endpoint: http://localhost:8080

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
