receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  presidio_redaction:
    presidio_endpoint: http://localhost:8080/anonymize

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
